// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getallquotes.sql

package database

import (
	"context"
)

const getAllQuotes = `-- name: GetAllQuotes :many
SELECT id, created_at, updated_at, quote, author, last_served_at
FROM quotes
ORDER BY created_at
`

func (q *Queries) GetAllQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quote,
			&i.Author,
			&i.LastServedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
