// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getrandom.sql

package database

import (
	"context"
	"database/sql"
)

const getRandom = `-- name: GetRandom :one
SELECT quote, author
FROM quotes
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomRow struct {
	Quote  string
	Author sql.NullString
}

func (q *Queries) GetRandom(ctx context.Context) (GetRandomRow, error) {
	row := q.db.QueryRowContext(ctx, getRandom)
	var i GetRandomRow
	err := row.Scan(&i.Quote, &i.Author)
	return i, err
}
