// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Quote struct {
	ID           interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Quote        string
	Author       sql.NullString
	LastServedAt sql.NullTime
}
