// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: putquote.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const putQuote = `-- name: PutQuote :one
INSERT INTO quotes (id, created_at, updated_at, quote, author, last_served_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    NULL
)
RETURNING id, created_at, updated_at, quote, author, last_served_at
`

type PutQuoteParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Quote     string
	Author    sql.NullString
}

func (q *Queries) PutQuote(ctx context.Context, arg PutQuoteParams) (Quote, error) {
	row := q.db.QueryRowContext(ctx, putQuote,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Quote,
		arg.Author,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quote,
		&i.Author,
		&i.LastServedAt,
	)
	return i, err
}
